apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
  namespace: app
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: hazelcast-service
  ports:
    - name: hazelcast
      port: 5701