apiVersion: v1
kind: Service
metadata:
  name: runner-service
  labels:
    name: runner-service
  namespace: app
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 30036
      name: tcp
  selector:
    name: runner-app