apiVersion: v1
kind: Service
metadata:
  name: runner-service
  labels:
    name: runner-service
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 30036
      protocol: TCP
  selector:
    app: runner-app